export const MODULE_DEFINITIONS = [
  {
    code: "dashboard",
    name: "Dashboard",
    description: "Tableau de bord de performance configurable",
    category: "core",
    isCore: true,
    sortOrder: 1,
  },
  {
    code: "hosmony",
    name: "Parcours HOSMONY",
    description: "Parcours de transformation en 5 niveaux",
    category: "core",
    isCore: true,
    sortOrder: 2,
  },
  {
    code: "actions",
    name: "Plan d'Actions",
    description: "Gestion des plans d'actions et suivi opérationnel",
    category: "core",
    isCore: true,
    sortOrder: 3,
  },
  {
    code: "evidence",
    name: "Preuves & Documents",
    description: "Gestion documentaire et preuves de conformité",
    category: "core",
    isCore: true,
    sortOrder: 4,
  },
  {
    code: "audit",
    name: "Audit & Certification",
    description: "Pré-audit, audit et processus de certification",
    category: "core",
    isCore: true,
    sortOrder: 5,
  },
  {
    code: "strategy",
    name: "Stratégie",
    description: "Structuration et suivi de la stratégie d'entreprise",
    category: "analytics",
    isCore: false,
    sortOrder: 6,
  },
  {
    code: "materiality",
    name: "Double Matérialité",
    description: "Analyse de matérialité ESG et financière",
    category: "analytics",
    isCore: false,
    sortOrder: 7,
  },
  {
    code: "stakeholders",
    name: "Parties Prenantes",
    description: "Cartographie et gestion des parties prenantes",
    category: "analytics",
    isCore: false,
    sortOrder: 8,
  },
  {
    code: "ai_studio",
    name: "Studio IA",
    description: "Création et gestion d'agents IA personnalisés",
    category: "ai",
    isCore: false,
    sortOrder: 9,
  },
  {
    code: "integrations",
    name: "Intégrations",
    description: "Connecteurs et synchronisation de données externes",
    category: "integration",
    isCore: false,
    sortOrder: 10,
  },
  {
    code: "opportunities",
    name: "Opportunités & Valeur",
    description: "Détection d'opportunités et suivi du ROI",
    category: "finance",
    isCore: false,
    sortOrder: 11,
  },
  {
    code: "marketplace",
    name: "Marketplace",
    description: "Publication et valorisation d'actifs hosmoniques",
    category: "finance",
    isCore: false,
    sortOrder: 12,
  },
  {
    code: "dynamics",
    name: "Dynamiques Internes",
    description: "Challenges, événements et engagement collaborateurs",
    category: "hr",
    isCore: false,
    sortOrder: 13,
  },
  {
    code: "competences",
    name: "MyDAD Compétences",
    description: "GPEC, cartographie et montée en compétences",
    category: "hr",
    isCore: false,
    sortOrder: 14,
  },
  {
    code: "pride",
    name: "PRIDE",
    description: "Mutualisation des ressources inter-entreprises",
    category: "operations",
    isCore: false,
    sortOrder: 15,
  },
] as const;

export type ModuleCode = (typeof MODULE_DEFINITIONS)[number]["code"];
