export const PERMISSIONS = {
  // Dashboard
  DASHBOARD_READ: "dashboard:read",
  DASHBOARD_WRITE: "dashboard:write",

  // KPI
  KPI_READ: "kpi:read",
  KPI_WRITE: "kpi:write",
  KPI_CONFIG: "kpi:config",

  // Config
  CONFIG_READ: "config:read",
  CONFIG_WRITE: "config:write",
  CONFIG_ADMIN: "config:admin",

  // Organization
  ORG_READ: "org:read",
  ORG_WRITE: "org:write",
  ORG_MEMBERS: "org:members",

  // Invitation
  INVITE_SEND: "invite:send",
  INVITE_MANAGE: "invite:manage",

  // Data
  DATA_READ: "data:read",
  DATA_WRITE: "data:write",
  DATA_SOURCE_MANAGE: "data:source:manage",

  // HOSMONY
  HOSMONY_READ: "hosmony:read",
  HOSMONY_MANAGE: "hosmony:manage",
  HOSMONY_AUDIT: "hosmony:audit",

  // Actions
  ACTION_READ: "action:read",
  ACTION_WRITE: "action:write",
  ACTION_MANAGE: "action:manage",

  // Evidence
  EVIDENCE_READ: "evidence:read",
  EVIDENCE_WRITE: "evidence:write",
  EVIDENCE_REVIEW: "evidence:review",

  // AI
  AI_READ: "ai:read",
  AI_USE: "ai:use",
  AI_MANAGE: "ai:manage",

  // Strategy
  STRATEGY_READ: "strategy:read",
  STRATEGY_WRITE: "strategy:write",

  // Materiality
  MATERIALITY_READ: "materiality:read",
  MATERIALITY_MANAGE: "materiality:manage",

  // Stakeholders
  STAKEHOLDER_READ: "stakeholder:read",
  STAKEHOLDER_MANAGE: "stakeholder:manage",

  // Opportunities
  OPPORTUNITY_READ: "opportunity:read",
  OPPORTUNITY_MANAGE: "opportunity:manage",

  // Assets
  ASSET_READ: "asset:read",
  ASSET_WRITE: "asset:write",
  ASSET_PUBLISH: "asset:publish",

  // Dynamics
  DYNAMICS_READ: "dynamics:read",
  DYNAMICS_WRITE: "dynamics:write",
  DYNAMICS_PARTICIPATE: "dynamics:participate",

  // Audit log
  AUDIT_LOG_READ: "audit_log:read",
} as const;

export const DEFAULT_ROLE_PERMISSIONS: Record<string, string[]> = {
  CONSULTANT: Object.values(PERMISSIONS),
  EXPERT_COMPTABLE: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.DASHBOARD_WRITE,
    PERMISSIONS.KPI_READ,
    PERMISSIONS.KPI_WRITE,
    PERMISSIONS.CONFIG_READ,
    PERMISSIONS.ORG_READ,
    PERMISSIONS.ORG_WRITE,
    PERMISSIONS.ORG_MEMBERS,
    PERMISSIONS.INVITE_SEND,
    PERMISSIONS.INVITE_MANAGE,
    PERMISSIONS.DATA_READ,
    PERMISSIONS.DATA_WRITE,
    PERMISSIONS.DATA_SOURCE_MANAGE,
    PERMISSIONS.HOSMONY_READ,
    PERMISSIONS.HOSMONY_MANAGE,
    PERMISSIONS.ACTION_READ,
    PERMISSIONS.ACTION_WRITE,
    PERMISSIONS.ACTION_MANAGE,
    PERMISSIONS.EVIDENCE_READ,
    PERMISSIONS.EVIDENCE_WRITE,
    PERMISSIONS.AI_READ,
    PERMISSIONS.AI_USE,
    PERMISSIONS.AI_MANAGE,
    PERMISSIONS.STRATEGY_READ,
    PERMISSIONS.STRATEGY_WRITE,
    PERMISSIONS.MATERIALITY_READ,
    PERMISSIONS.STAKEHOLDER_READ,
    PERMISSIONS.STAKEHOLDER_MANAGE,
    PERMISSIONS.OPPORTUNITY_READ,
    PERMISSIONS.OPPORTUNITY_MANAGE,
    PERMISSIONS.ASSET_READ,
    PERMISSIONS.ASSET_WRITE,
    PERMISSIONS.DYNAMICS_READ,
    PERMISSIONS.DYNAMICS_WRITE,
  ],
  DIRIGEANT: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.DASHBOARD_WRITE,
    PERMISSIONS.KPI_READ,
    PERMISSIONS.KPI_WRITE,
    PERMISSIONS.ORG_READ,
    PERMISSIONS.ORG_WRITE,
    PERMISSIONS.ORG_MEMBERS,
    PERMISSIONS.INVITE_SEND,
    PERMISSIONS.DATA_READ,
    PERMISSIONS.DATA_WRITE,
    PERMISSIONS.HOSMONY_READ,
    PERMISSIONS.ACTION_READ,
    PERMISSIONS.ACTION_WRITE,
    PERMISSIONS.EVIDENCE_READ,
    PERMISSIONS.EVIDENCE_WRITE,
    PERMISSIONS.AI_READ,
    PERMISSIONS.AI_USE,
    PERMISSIONS.STRATEGY_READ,
    PERMISSIONS.MATERIALITY_READ,
    PERMISSIONS.STAKEHOLDER_READ,
    PERMISSIONS.OPPORTUNITY_READ,
    PERMISSIONS.ASSET_READ,
    PERMISSIONS.ASSET_WRITE,
    PERMISSIONS.DYNAMICS_READ,
    PERMISSIONS.DYNAMICS_WRITE,
  ],
  COLLABORATEUR: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.KPI_READ,
    PERMISSIONS.HOSMONY_READ,
    PERMISSIONS.ACTION_READ,
    PERMISSIONS.ACTION_WRITE,
    PERMISSIONS.EVIDENCE_READ,
    PERMISSIONS.EVIDENCE_WRITE,
    PERMISSIONS.AI_READ,
    PERMISSIONS.AI_USE,
    PERMISSIONS.DYNAMICS_READ,
    PERMISSIONS.DYNAMICS_PARTICIPATE,
  ],
};
